//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dvo_ros package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dvo_ros__CAMERADENSETRACKERCONFIG_H__
#define __dvo_ros__CAMERADENSETRACKERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dvo_ros
{
  class CameraDenseTrackerConfigStatics;

  class CameraDenseTrackerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(CameraDenseTrackerConfig &config, const CameraDenseTrackerConfig &max, const CameraDenseTrackerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const CameraDenseTrackerConfig &config1, const CameraDenseTrackerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, CameraDenseTrackerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const CameraDenseTrackerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CameraDenseTrackerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const CameraDenseTrackerConfig &config) const = 0;
      virtual void getValue(const CameraDenseTrackerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T CameraDenseTrackerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (CameraDenseTrackerConfig::* field);

      virtual void clamp(CameraDenseTrackerConfig &config, const CameraDenseTrackerConfig &max, const CameraDenseTrackerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const CameraDenseTrackerConfig &config1, const CameraDenseTrackerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, CameraDenseTrackerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const CameraDenseTrackerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CameraDenseTrackerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const CameraDenseTrackerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const CameraDenseTrackerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, CameraDenseTrackerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, CameraDenseTrackerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<CameraDenseTrackerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(CameraDenseTrackerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("run_dense_tracking"==(*_i)->name){run_dense_tracking = boost::any_cast<bool>(val);}
        if("use_dense_tracking_estimate"==(*_i)->name){use_dense_tracking_estimate = boost::any_cast<bool>(val);}
        if("coarsest_level"==(*_i)->name){coarsest_level = boost::any_cast<int>(val);}
        if("finest_level"==(*_i)->name){finest_level = boost::any_cast<int>(val);}
        if("max_iterations"==(*_i)->name){max_iterations = boost::any_cast<int>(val);}
        if("precision"==(*_i)->name){precision = boost::any_cast<double>(val);}
        if("use_initial_estimate"==(*_i)->name){use_initial_estimate = boost::any_cast<bool>(val);}
        if("use_weighting"==(*_i)->name){use_weighting = boost::any_cast<bool>(val);}
        if("scale_estimator"==(*_i)->name){scale_estimator = boost::any_cast<int>(val);}
        if("scale_estimator_param"==(*_i)->name){scale_estimator_param = boost::any_cast<double>(val);}
        if("influence_function"==(*_i)->name){influence_function = boost::any_cast<int>(val);}
        if("influence_function_param"==(*_i)->name){influence_function_param = boost::any_cast<double>(val);}
        if("min_intensity_deriv"==(*_i)->name){min_intensity_deriv = boost::any_cast<double>(val);}
        if("min_depth_deriv"==(*_i)->name){min_depth_deriv = boost::any_cast<double>(val);}
        if("lambda"==(*_i)->name){lambda = boost::any_cast<double>(val);}
        if("mu"==(*_i)->name){mu = boost::any_cast<double>(val);}
        if("reconstruction"==(*_i)->name){reconstruction = boost::any_cast<bool>(val);}
      }
    }

    bool run_dense_tracking;
bool use_dense_tracking_estimate;
int coarsest_level;
int finest_level;
int max_iterations;
double precision;
bool use_initial_estimate;
bool use_weighting;
int scale_estimator;
double scale_estimator_param;
int influence_function;
double influence_function_param;
double min_intensity_deriv;
double min_depth_deriv;
double lambda;
double mu;
bool reconstruction;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool run_dense_tracking;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_dense_tracking_estimate;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int coarsest_level;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int finest_level;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_iterations;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double precision;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_initial_estimate;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_weighting;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int scale_estimator;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double scale_estimator_param;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int influence_function;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double influence_function_param;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_intensity_deriv;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_depth_deriv;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lambda;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mu;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool reconstruction;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("CameraDenseTrackerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const CameraDenseTrackerConfig &__max__ = __getMax__();
      const CameraDenseTrackerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const CameraDenseTrackerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const CameraDenseTrackerConfig &__getDefault__();
    static const CameraDenseTrackerConfig &__getMax__();
    static const CameraDenseTrackerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const CameraDenseTrackerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void CameraDenseTrackerConfig::ParamDescription<std::string>::clamp(CameraDenseTrackerConfig &config, const CameraDenseTrackerConfig &max, const CameraDenseTrackerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class CameraDenseTrackerConfigStatics
  {
    friend class CameraDenseTrackerConfig;

    CameraDenseTrackerConfigStatics()
    {
CameraDenseTrackerConfig::GroupDescription<CameraDenseTrackerConfig::DEFAULT, CameraDenseTrackerConfig> Default("Default", "", 0, 0, true, &CameraDenseTrackerConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.run_dense_tracking = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.run_dense_tracking = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.run_dense_tracking = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("run_dense_tracking", "bool", 1, "", "", &CameraDenseTrackerConfig::run_dense_tracking)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("run_dense_tracking", "bool", 1, "", "", &CameraDenseTrackerConfig::run_dense_tracking)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_dense_tracking_estimate = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_dense_tracking_estimate = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_dense_tracking_estimate = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("use_dense_tracking_estimate", "bool", 2, "", "", &CameraDenseTrackerConfig::use_dense_tracking_estimate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("use_dense_tracking_estimate", "bool", 2, "", "", &CameraDenseTrackerConfig::use_dense_tracking_estimate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.coarsest_level = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.coarsest_level = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.coarsest_level = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("coarsest_level", "int", 4, "", "", &CameraDenseTrackerConfig::coarsest_level)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("coarsest_level", "int", 4, "", "", &CameraDenseTrackerConfig::coarsest_level)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.finest_level = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.finest_level = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.finest_level = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("finest_level", "int", 4, "", "", &CameraDenseTrackerConfig::finest_level)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("finest_level", "int", 4, "", "", &CameraDenseTrackerConfig::finest_level)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_iterations = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_iterations = 500;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_iterations = 50;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("max_iterations", "int", 4, "", "", &CameraDenseTrackerConfig::max_iterations)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("max_iterations", "int", 4, "", "", &CameraDenseTrackerConfig::max_iterations)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.precision = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.precision = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.precision = 0.0001;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("precision", "double", 4, "", "", &CameraDenseTrackerConfig::precision)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("precision", "double", 4, "", "", &CameraDenseTrackerConfig::precision)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_initial_estimate = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_initial_estimate = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_initial_estimate = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("use_initial_estimate", "bool", 4, "", "", &CameraDenseTrackerConfig::use_initial_estimate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("use_initial_estimate", "bool", 4, "", "", &CameraDenseTrackerConfig::use_initial_estimate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_weighting = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_weighting = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_weighting = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("use_weighting", "bool", 4, "", "", &CameraDenseTrackerConfig::use_weighting)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("use_weighting", "bool", 4, "", "", &CameraDenseTrackerConfig::use_weighting)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.scale_estimator = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.scale_estimator = 20;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.scale_estimator = 2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("scale_estimator", "int", 4, "", "{'enum_description': 'scale estimator', 'enum': [{'srcline': 26, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'NormalDistributionScaleEstimator'}, {'srcline': 27, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'TDistributionScaleEstimator'}, {'srcline': 28, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'MADScaleEstimator'}]}", &CameraDenseTrackerConfig::scale_estimator)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("scale_estimator", "int", 4, "", "{'enum_description': 'scale estimator', 'enum': [{'srcline': 26, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'NormalDistributionScaleEstimator'}, {'srcline': 27, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'TDistributionScaleEstimator'}, {'srcline': 28, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'MADScaleEstimator'}]}", &CameraDenseTrackerConfig::scale_estimator)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.scale_estimator_param = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.scale_estimator_param = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.scale_estimator_param = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("scale_estimator_param", "double", 4, "", "", &CameraDenseTrackerConfig::scale_estimator_param)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("scale_estimator_param", "double", 4, "", "", &CameraDenseTrackerConfig::scale_estimator_param)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.influence_function = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.influence_function = 20;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.influence_function = 2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("influence_function", "int", 4, "", "{'enum_description': 'influence function', 'enum': [{'srcline': 33, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'TukeyInfluenceFunction'}, {'srcline': 34, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'TDistributionInfluenceFunction'}, {'srcline': 35, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'HuberInfluenceFunction'}]}", &CameraDenseTrackerConfig::influence_function)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<int>("influence_function", "int", 4, "", "{'enum_description': 'influence function', 'enum': [{'srcline': 33, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'TukeyInfluenceFunction'}, {'srcline': 34, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'TDistributionInfluenceFunction'}, {'srcline': 35, 'description': '', 'srcfile': '/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'HuberInfluenceFunction'}]}", &CameraDenseTrackerConfig::influence_function)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.influence_function_param = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.influence_function_param = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.influence_function_param = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("influence_function_param", "double", 4, "", "", &CameraDenseTrackerConfig::influence_function_param)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("influence_function_param", "double", 4, "", "", &CameraDenseTrackerConfig::influence_function_param)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_intensity_deriv = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_intensity_deriv = 255.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_intensity_deriv = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("min_intensity_deriv", "double", 4, "", "", &CameraDenseTrackerConfig::min_intensity_deriv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("min_intensity_deriv", "double", 4, "", "", &CameraDenseTrackerConfig::min_intensity_deriv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_depth_deriv = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_depth_deriv = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_depth_deriv = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("min_depth_deriv", "double", 4, "", "", &CameraDenseTrackerConfig::min_depth_deriv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("min_depth_deriv", "double", 4, "", "", &CameraDenseTrackerConfig::min_depth_deriv)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lambda = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lambda = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lambda = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("lambda", "double", 4, "", "", &CameraDenseTrackerConfig::lambda)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("lambda", "double", 4, "", "", &CameraDenseTrackerConfig::lambda)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mu = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mu = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mu = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("mu", "double", 4, "", "", &CameraDenseTrackerConfig::mu)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<double>("mu", "double", 4, "", "", &CameraDenseTrackerConfig::mu)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.reconstruction = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.reconstruction = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.reconstruction = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("reconstruction", "bool", 8, "", "", &CameraDenseTrackerConfig::reconstruction)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr(new CameraDenseTrackerConfig::ParamDescription<bool>("reconstruction", "bool", 8, "", "", &CameraDenseTrackerConfig::reconstruction)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(CameraDenseTrackerConfig::AbstractGroupDescriptionConstPtr(new CameraDenseTrackerConfig::GroupDescription<CameraDenseTrackerConfig::DEFAULT, CameraDenseTrackerConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<CameraDenseTrackerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<CameraDenseTrackerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    CameraDenseTrackerConfig __max__;
    CameraDenseTrackerConfig __min__;
    CameraDenseTrackerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const CameraDenseTrackerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static CameraDenseTrackerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &CameraDenseTrackerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const CameraDenseTrackerConfig &CameraDenseTrackerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const CameraDenseTrackerConfig &CameraDenseTrackerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const CameraDenseTrackerConfig &CameraDenseTrackerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<CameraDenseTrackerConfig::AbstractParamDescriptionConstPtr> &CameraDenseTrackerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<CameraDenseTrackerConfig::AbstractGroupDescriptionConstPtr> &CameraDenseTrackerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const CameraDenseTrackerConfigStatics *CameraDenseTrackerConfig::__get_statics__()
  {
    const static CameraDenseTrackerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = CameraDenseTrackerConfigStatics::get_instance();

    return statics;
  }

//#line 16 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_RunDenseTracking = 1;
//#line 17 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_UseDenseTrackingEstimate = 2;
//#line 18 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_ConfigParam = 4;
//#line 19 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_MiscParam = 8;
//#line 26 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_NormalDistributionScaleEstimator = 1;
//#line 27 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_TDistributionScaleEstimator = 2;
//#line 28 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_MADScaleEstimator = 3;
//#line 33 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_TukeyInfluenceFunction = 1;
//#line 34 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_TDistributionInfluenceFunction = 2;
//#line 35 "/home/smarlogy/catkin_ws/src/dvo_slam/dvo_ros/cfg/CameraDenseTracker.cfg"
      const int CameraDenseTracker_HuberInfluenceFunction = 3;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CAMERADENSETRACKERRECONFIGURATOR_H__
