// Generated by gencpp from file mrpt_msgs/GetCMGraph.msg
// DO NOT EDIT!


#ifndef MRPT_MSGS_MESSAGE_GETCMGRAPH_H
#define MRPT_MSGS_MESSAGE_GETCMGRAPH_H

#include <ros/service_traits.h>


#include <mrpt_msgs/GetCMGraphRequest.h>
#include <mrpt_msgs/GetCMGraphResponse.h>


namespace mrpt_msgs
{

struct GetCMGraph
{

typedef GetCMGraphRequest Request;
typedef GetCMGraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCMGraph
} // namespace mrpt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrpt_msgs::GetCMGraph > {
  static const char* value()
  {
    return "42fe1c3f75b229167d9c830777c38406";
  }

  static const char* value(const ::mrpt_msgs::GetCMGraph&) { return value(); }
};

template<>
struct DataType< ::mrpt_msgs::GetCMGraph > {
  static const char* value()
  {
    return "mrpt_msgs/GetCMGraph";
  }

  static const char* value(const ::mrpt_msgs::GetCMGraph&) { return value(); }
};


// service_traits::MD5Sum< ::mrpt_msgs::GetCMGraphRequest> should match 
// service_traits::MD5Sum< ::mrpt_msgs::GetCMGraph > 
template<>
struct MD5Sum< ::mrpt_msgs::GetCMGraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrpt_msgs::GetCMGraph >::value();
  }
  static const char* value(const ::mrpt_msgs::GetCMGraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrpt_msgs::GetCMGraphRequest> should match 
// service_traits::DataType< ::mrpt_msgs::GetCMGraph > 
template<>
struct DataType< ::mrpt_msgs::GetCMGraphRequest>
{
  static const char* value()
  {
    return DataType< ::mrpt_msgs::GetCMGraph >::value();
  }
  static const char* value(const ::mrpt_msgs::GetCMGraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrpt_msgs::GetCMGraphResponse> should match 
// service_traits::MD5Sum< ::mrpt_msgs::GetCMGraph > 
template<>
struct MD5Sum< ::mrpt_msgs::GetCMGraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrpt_msgs::GetCMGraph >::value();
  }
  static const char* value(const ::mrpt_msgs::GetCMGraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrpt_msgs::GetCMGraphResponse> should match 
// service_traits::DataType< ::mrpt_msgs::GetCMGraph > 
template<>
struct DataType< ::mrpt_msgs::GetCMGraphResponse>
{
  static const char* value()
  {
    return DataType< ::mrpt_msgs::GetCMGraph >::value();
  }
  static const char* value(const ::mrpt_msgs::GetCMGraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MRPT_MSGS_MESSAGE_GETCMGRAPH_H
