// Generated by gencpp from file mrpt_msgs/GetCMGraphRequest.msg
// DO NOT EDIT!


#ifndef MRPT_MSGS_MESSAGE_GETCMGRAPHREQUEST_H
#define MRPT_MSGS_MESSAGE_GETCMGRAPHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrpt_msgs
{
template <class ContainerAllocator>
struct GetCMGraphRequest_
{
  typedef GetCMGraphRequest_<ContainerAllocator> Type;

  GetCMGraphRequest_()
    : nodeIDs()  {
    }
  GetCMGraphRequest_(const ContainerAllocator& _alloc)
    : nodeIDs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _nodeIDs_type;
  _nodeIDs_type nodeIDs;





  typedef boost::shared_ptr< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCMGraphRequest_

typedef ::mrpt_msgs::GetCMGraphRequest_<std::allocator<void> > GetCMGraphRequest;

typedef boost::shared_ptr< ::mrpt_msgs::GetCMGraphRequest > GetCMGraphRequestPtr;
typedef boost::shared_ptr< ::mrpt_msgs::GetCMGraphRequest const> GetCMGraphRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrpt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mrpt_msgs': ['/home/smarlogy/catkin_ws/src/mrpt_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f27c6ad84ac86a19b3f9376555dd464";
  }

  static const char* value(const ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f27c6ad84ac86a1ULL;
  static const uint64_t static_value2 = 0x9b3f9376555dd464ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrpt_msgs/GetCMGraphRequest";
  }

  static const char* value(const ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
uint64[] nodeIDs\n\
";
  }

  static const char* value(const ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeIDs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCMGraphRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrpt_msgs::GetCMGraphRequest_<ContainerAllocator>& v)
  {
    s << indent << "nodeIDs[]" << std::endl;
    for (size_t i = 0; i < v.nodeIDs.size(); ++i)
    {
      s << indent << "  nodeIDs[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.nodeIDs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRPT_MSGS_MESSAGE_GETCMGRAPHREQUEST_H
