// Generated by gencpp from file mrpt_msgs/GraphConstraint.msg
// DO NOT EDIT!


#ifndef MRPT_MSGS_MESSAGE_GRAPHCONSTRAINT_H
#define MRPT_MSGS_MESSAGE_GRAPHCONSTRAINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovariance.h>

namespace mrpt_msgs
{
template <class ContainerAllocator>
struct GraphConstraint_
{
  typedef GraphConstraint_<ContainerAllocator> Type;

  GraphConstraint_()
    : nodeID_from(0)
    , nodeID_to(0)
    , constraint()  {
    }
  GraphConstraint_(const ContainerAllocator& _alloc)
    : nodeID_from(0)
    , nodeID_to(0)
    , constraint(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _nodeID_from_type;
  _nodeID_from_type nodeID_from;

   typedef uint64_t _nodeID_to_type;
  _nodeID_to_type nodeID_to;

   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _constraint_type;
  _constraint_type constraint;





  typedef boost::shared_ptr< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> const> ConstPtr;

}; // struct GraphConstraint_

typedef ::mrpt_msgs::GraphConstraint_<std::allocator<void> > GraphConstraint;

typedef boost::shared_ptr< ::mrpt_msgs::GraphConstraint > GraphConstraintPtr;
typedef boost::shared_ptr< ::mrpt_msgs::GraphConstraint const> GraphConstraintConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrpt_msgs::GraphConstraint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrpt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mrpt_msgs': ['/home/smarlogy/catkin_ws/src/mrpt_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27a8223828dcd501cdc97873eecdd09e";
  }

  static const char* value(const ::mrpt_msgs::GraphConstraint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27a8223828dcd501ULL;
  static const uint64_t static_value2 = 0xcdc97873eecdd09eULL;
};

template<class ContainerAllocator>
struct DataType< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrpt_msgs/GraphConstraint";
  }

  static const char* value(const ::mrpt_msgs::GraphConstraint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Graph constraint that connects 2 nodes\n\
#\n\
# Currently used in the mrpt_graphslam_2d ROS application.\n\
\n\
uint64 nodeID_from\n\
uint64 nodeID_to\n\
geometry_msgs/PoseWithCovariance constraint\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::mrpt_msgs::GraphConstraint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeID_from);
      stream.next(m.nodeID_to);
      stream.next(m.constraint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraphConstraint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrpt_msgs::GraphConstraint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrpt_msgs::GraphConstraint_<ContainerAllocator>& v)
  {
    s << indent << "nodeID_from: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.nodeID_from);
    s << indent << "nodeID_to: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.nodeID_to);
    s << indent << "constraint: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.constraint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRPT_MSGS_MESSAGE_GRAPHCONSTRAINT_H
