// Generated by gencpp from file mrpt_msgs/NodeIDWithLaserScan.msg
// DO NOT EDIT!


#ifndef MRPT_MSGS_MESSAGE_NODEIDWITHLASERSCAN_H
#define MRPT_MSGS_MESSAGE_NODEIDWITHLASERSCAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/LaserScan.h>

namespace mrpt_msgs
{
template <class ContainerAllocator>
struct NodeIDWithLaserScan_
{
  typedef NodeIDWithLaserScan_<ContainerAllocator> Type;

  NodeIDWithLaserScan_()
    : nodeID(0)
    , scan()  {
    }
  NodeIDWithLaserScan_(const ContainerAllocator& _alloc)
    : nodeID(0)
    , scan(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _nodeID_type;
  _nodeID_type nodeID;

   typedef  ::sensor_msgs::LaserScan_<ContainerAllocator>  _scan_type;
  _scan_type scan;





  typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> const> ConstPtr;

}; // struct NodeIDWithLaserScan_

typedef ::mrpt_msgs::NodeIDWithLaserScan_<std::allocator<void> > NodeIDWithLaserScan;

typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithLaserScan > NodeIDWithLaserScanPtr;
typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithLaserScan const> NodeIDWithLaserScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrpt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mrpt_msgs': ['/home/smarlogy/catkin_ws/src/mrpt_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "135d436b647c8470f71b2c97722a4352";
  }

  static const char* value(const ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x135d436b647c8470ULL;
  static const uint64_t static_value2 = 0xf71b2c97722a4352ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrpt_msgs/NodeIDWithLaserScan";
  }

  static const char* value(const ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# NodeID along with the associated LaserScan\n\
#\n\
# Currently used in the mrpt_graphslam_2d ROS application.\n\
\n\
uint64 nodeID\n\
sensor_msgs/LaserScan scan\n\
\n\
================================================================================\n\
MSG: sensor_msgs/LaserScan\n\
# Single scan from a planar laser range-finder\n\
#\n\
# If you have another ranging device with different behavior (e.g. a sonar\n\
# array), please find or create a different message, since applications\n\
# will make fairly laser-specific assumptions about this data\n\
\n\
Header header            # timestamp in the header is the acquisition time of \n\
                         # the first ray in the scan.\n\
                         #\n\
                         # in frame frame_id, angles are measured around \n\
                         # the positive Z axis (counterclockwise, if Z is up)\n\
                         # with zero angle being forward along the x axis\n\
                         \n\
float32 angle_min        # start angle of the scan [rad]\n\
float32 angle_max        # end angle of the scan [rad]\n\
float32 angle_increment  # angular distance between measurements [rad]\n\
\n\
float32 time_increment   # time between measurements [seconds] - if your scanner\n\
                         # is moving, this will be used in interpolating position\n\
                         # of 3d points\n\
float32 scan_time        # time between scans [seconds]\n\
\n\
float32 range_min        # minimum range value [m]\n\
float32 range_max        # maximum range value [m]\n\
\n\
float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n\
float32[] intensities    # intensity data [device-specific units].  If your\n\
                         # device does not provide intensities, please leave\n\
                         # the array empty.\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeID);
      stream.next(m.scan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeIDWithLaserScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrpt_msgs::NodeIDWithLaserScan_<ContainerAllocator>& v)
  {
    s << indent << "nodeID: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.nodeID);
    s << indent << "scan: ";
    s << std::endl;
    Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "  ", v.scan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRPT_MSGS_MESSAGE_NODEIDWITHLASERSCAN_H
