// Generated by gencpp from file mrpt_msgs/NodeIDWithPose.msg
// DO NOT EDIT!


#ifndef MRPT_MSGS_MESSAGE_NODEIDWITHPOSE_H
#define MRPT_MSGS_MESSAGE_NODEIDWITHPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <std_msgs/String.h>

namespace mrpt_msgs
{
template <class ContainerAllocator>
struct NodeIDWithPose_
{
  typedef NodeIDWithPose_<ContainerAllocator> Type;

  NodeIDWithPose_()
    : nodeID(0)
    , pose()
    , str_ID()
    , nodeID_loc(0)  {
    }
  NodeIDWithPose_(const ContainerAllocator& _alloc)
    : nodeID(0)
    , pose(_alloc)
    , str_ID(_alloc)
    , nodeID_loc(0)  {
  (void)_alloc;
    }



   typedef uint64_t _nodeID_type;
  _nodeID_type nodeID;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::std_msgs::String_<ContainerAllocator>  _str_ID_type;
  _str_ID_type str_ID;

   typedef uint64_t _nodeID_loc_type;
  _nodeID_loc_type nodeID_loc;





  typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> const> ConstPtr;

}; // struct NodeIDWithPose_

typedef ::mrpt_msgs::NodeIDWithPose_<std::allocator<void> > NodeIDWithPose;

typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithPose > NodeIDWithPosePtr;
typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithPose const> NodeIDWithPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrpt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mrpt_msgs': ['/home/smarlogy/catkin_ws/src/mrpt_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87c8db37a689c10a5c5dc1aa39838320";
  }

  static const char* value(const ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87c8db37a689c10aULL;
  static const uint64_t static_value2 = 0x5c5dc1aa39838320ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrpt_msgs/NodeIDWithPose";
  }

  static const char* value(const ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# NodeID along with its corresponding 2D/3D pose estimation.\n\
# Message also contains the following optional fields:\n\
# - str_ID: string identifier of the robot agent that initially registered this node in\n\
# its graph\n\
# - nodeID_loc: ID of the current node in the graph it was initially registered in.\n\
#\n\
# note: Additional fields correspond to the fields of the\n\
# mrpt::graphs::detail::TMRSlamNodeAnnotations struct\n\
#\n\
# Currently used in the mrpt_graphslam_2d ROS application.\n\
\n\
uint64 nodeID\n\
geometry_msgs/Pose pose\n\
\n\
std_msgs/String str_ID\n\
uint64 nodeID_loc\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeID);
      stream.next(m.pose);
      stream.next(m.str_ID);
      stream.next(m.nodeID_loc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeIDWithPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator>& v)
  {
    s << indent << "nodeID: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.nodeID);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "str_ID: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.str_ID);
    s << indent << "nodeID_loc: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.nodeID_loc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRPT_MSGS_MESSAGE_NODEIDWITHPOSE_H
