// Generated by gencpp from file mrpt_msgs/NodeIDWithPose_vec.msg
// DO NOT EDIT!


#ifndef MRPT_MSGS_MESSAGE_NODEIDWITHPOSE_VEC_H
#define MRPT_MSGS_MESSAGE_NODEIDWITHPOSE_VEC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mrpt_msgs/NodeIDWithPose.h>

namespace mrpt_msgs
{
template <class ContainerAllocator>
struct NodeIDWithPose_vec_
{
  typedef NodeIDWithPose_vec_<ContainerAllocator> Type;

  NodeIDWithPose_vec_()
    : vec()  {
    }
  NodeIDWithPose_vec_(const ContainerAllocator& _alloc)
    : vec(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >::other >  _vec_type;
  _vec_type vec;





  typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> const> ConstPtr;

}; // struct NodeIDWithPose_vec_

typedef ::mrpt_msgs::NodeIDWithPose_vec_<std::allocator<void> > NodeIDWithPose_vec;

typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithPose_vec > NodeIDWithPose_vecPtr;
typedef boost::shared_ptr< ::mrpt_msgs::NodeIDWithPose_vec const> NodeIDWithPose_vecConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrpt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mrpt_msgs': ['/home/smarlogy/catkin_ws/src/mrpt_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f30000109eab9cc7bc6b44c3e86d9fac";
  }

  static const char* value(const ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf30000109eab9cc7ULL;
  static const uint64_t static_value2 = 0xbc6b44c3e86d9facULL;
};

template<class ContainerAllocator>
struct DataType< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrpt_msgs/NodeIDWithPose_vec";
  }

  static const char* value(const ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Vector of NodeIDWithPose msgs\n\
\n\
NodeIDWithPose[] vec\n\
\n\
\n\
================================================================================\n\
MSG: mrpt_msgs/NodeIDWithPose\n\
# NodeID along with its corresponding 2D/3D pose estimation.\n\
# Message also contains the following optional fields:\n\
# - str_ID: string identifier of the robot agent that initially registered this node in\n\
# its graph\n\
# - nodeID_loc: ID of the current node in the graph it was initially registered in.\n\
#\n\
# note: Additional fields correspond to the fields of the\n\
# mrpt::graphs::detail::TMRSlamNodeAnnotations struct\n\
#\n\
# Currently used in the mrpt_graphslam_2d ROS application.\n\
\n\
uint64 nodeID\n\
geometry_msgs/Pose pose\n\
\n\
std_msgs/String str_ID\n\
uint64 nodeID_loc\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeIDWithPose_vec_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrpt_msgs::NodeIDWithPose_vec_<ContainerAllocator>& v)
  {
    s << indent << "vec[]" << std::endl;
    for (size_t i = 0; i < v.vec.size(); ++i)
    {
      s << indent << "  vec[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mrpt_msgs::NodeIDWithPose_<ContainerAllocator> >::stream(s, indent + "    ", v.vec[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRPT_MSGS_MESSAGE_NODEIDWITHPOSE_VEC_H
