// Generated by gencpp from file marker_msgs/MarkerDetection.msg
// DO NOT EDIT!


#ifndef MARKER_MSGS_MESSAGE_MARKERDETECTION_H
#define MARKER_MSGS_MESSAGE_MARKERDETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <marker_msgs/Marker.h>

namespace marker_msgs
{
template <class ContainerAllocator>
struct MarkerDetection_
{
  typedef MarkerDetection_<ContainerAllocator> Type;

  MarkerDetection_()
    : header()
    , distance_min(0.0)
    , distance_max(0.0)
    , distance_max_id(0.0)
    , view_direction()
    , fov_horizontal(0.0)
    , fov_vertical(0.0)
    , type()
    , markers()  {
    }
  MarkerDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance_min(0.0)
    , distance_max(0.0)
    , distance_max_id(0.0)
    , view_direction(_alloc)
    , fov_horizontal(0.0)
    , fov_vertical(0.0)
    , type(_alloc)
    , markers(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _distance_min_type;
  _distance_min_type distance_min;

   typedef float _distance_max_type;
  _distance_max_type distance_max;

   typedef float _distance_max_id_type;
  _distance_max_id_type distance_max_id;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _view_direction_type;
  _view_direction_type view_direction;

   typedef float _fov_horizontal_type;
  _fov_horizontal_type fov_horizontal;

   typedef float _fov_vertical_type;
  _fov_vertical_type fov_vertical;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::vector< ::marker_msgs::Marker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::marker_msgs::Marker_<ContainerAllocator> >::other >  _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::marker_msgs::MarkerDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marker_msgs::MarkerDetection_<ContainerAllocator> const> ConstPtr;

}; // struct MarkerDetection_

typedef ::marker_msgs::MarkerDetection_<std::allocator<void> > MarkerDetection;

typedef boost::shared_ptr< ::marker_msgs::MarkerDetection > MarkerDetectionPtr;
typedef boost::shared_ptr< ::marker_msgs::MarkerDetection const> MarkerDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marker_msgs::MarkerDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marker_msgs::MarkerDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace marker_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'marker_msgs': ['/home/smarlogy/catkin_ws/src/marker_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::marker_msgs::MarkerDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marker_msgs::MarkerDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_msgs::MarkerDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_msgs::MarkerDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_msgs::MarkerDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_msgs::MarkerDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marker_msgs::MarkerDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b17d48b7aeec842456674ad3657d85fc";
  }

  static const char* value(const ::marker_msgs::MarkerDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb17d48b7aeec8424ULL;
  static const uint64_t static_value2 = 0x56674ad3657d85fcULL;
};

template<class ContainerAllocator>
struct DataType< ::marker_msgs::MarkerDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marker_msgs/MarkerDetection";
  }

  static const char* value(const ::marker_msgs::MarkerDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marker_msgs::MarkerDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This expresses a marker/fiducial detection\n\
Header header                  # timestamp in the header is the acquisition time and frame\n\
\n\
float32 distance_min           # distance minimum range value [m]\n\
float32 distance_max           # distance maximum range value [m]\n\
float32 distance_max_id        # distance maximum range value to detect id [m]\n\
\n\
geometry_msgs/Quaternion view_direction       # view direction\n\
float32 fov_horizontal                        # field of view horizontal [rad]\n\
float32 fov_vertical                          # field of view vertical [rad]\n\
\n\
string   type                  # marker type used (bch, artag, mip_36h12, stage, ...)\n\
Marker[] markers               # detected markers\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: marker_msgs/Marker\n\
# This expresses a marker/fiducial in a 3D space\n\
int32[] ids                  # possible ids of the detected fiducial (empty if no id could be identified)\n\
float64[] ids_confidence     # confidence of the possible ids in [0, 1]\n\
geometry_msgs/Pose pose      # pose of the detected marker/fiducial\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::marker_msgs::MarkerDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marker_msgs::MarkerDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance_min);
      stream.next(m.distance_max);
      stream.next(m.distance_max_id);
      stream.next(m.view_direction);
      stream.next(m.fov_horizontal);
      stream.next(m.fov_vertical);
      stream.next(m.type);
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkerDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marker_msgs::MarkerDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marker_msgs::MarkerDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance_min: ";
    Printer<float>::stream(s, indent + "  ", v.distance_min);
    s << indent << "distance_max: ";
    Printer<float>::stream(s, indent + "  ", v.distance_max);
    s << indent << "distance_max_id: ";
    Printer<float>::stream(s, indent + "  ", v.distance_max_id);
    s << indent << "view_direction: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.view_direction);
    s << indent << "fov_horizontal: ";
    Printer<float>::stream(s, indent + "  ", v.fov_horizontal);
    s << indent << "fov_vertical: ";
    Printer<float>::stream(s, indent + "  ", v.fov_vertical);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::marker_msgs::Marker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARKER_MSGS_MESSAGE_MARKERDETECTION_H
