//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dvo_slam package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dvo_slam__KEYFRAMESLAMCONFIG_H__
#define __dvo_slam__KEYFRAMESLAMCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dvo_slam
{
  class KeyframeSlamConfigStatics;

  class KeyframeSlamConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(KeyframeSlamConfig &config, const KeyframeSlamConfig &max, const KeyframeSlamConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const KeyframeSlamConfig &config1, const KeyframeSlamConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, KeyframeSlamConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const KeyframeSlamConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, KeyframeSlamConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const KeyframeSlamConfig &config) const = 0;
      virtual void getValue(const KeyframeSlamConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T KeyframeSlamConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (KeyframeSlamConfig::* field);

      virtual void clamp(KeyframeSlamConfig &config, const KeyframeSlamConfig &max, const KeyframeSlamConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const KeyframeSlamConfig &config1, const KeyframeSlamConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, KeyframeSlamConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const KeyframeSlamConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, KeyframeSlamConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const KeyframeSlamConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const KeyframeSlamConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, KeyframeSlamConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, KeyframeSlamConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<KeyframeSlamConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(KeyframeSlamConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_translational_distance"==(*_i)->name){max_translational_distance = boost::any_cast<double>(val);}
        if("max_rotational_distance"==(*_i)->name){max_rotational_distance = boost::any_cast<double>(val);}
        if("min_entropy_ratio"==(*_i)->name){min_entropy_ratio = boost::any_cast<double>(val);}
        if("min_eq_sys_constraint_ratio"==(*_i)->name){min_eq_sys_constraint_ratio = boost::any_cast<double>(val);}
        if("constraint_search_radius"==(*_i)->name){constraint_search_radius = boost::any_cast<double>(val);}
        if("constraint_min_entropy_ratio_coarse"==(*_i)->name){constraint_min_entropy_ratio_coarse = boost::any_cast<double>(val);}
        if("constraint_min_entropy_ratio_fine"==(*_i)->name){constraint_min_entropy_ratio_fine = boost::any_cast<double>(val);}
        if("constraint_min_eq_sys_constraint_ratio"==(*_i)->name){constraint_min_eq_sys_constraint_ratio = boost::any_cast<double>(val);}
        if("graph_opt_robust"==(*_i)->name){graph_opt_robust = boost::any_cast<bool>(val);}
        if("graph_opt_iterations"==(*_i)->name){graph_opt_iterations = boost::any_cast<int>(val);}
        if("graph_opt_dense_graph"==(*_i)->name){graph_opt_dense_graph = boost::any_cast<bool>(val);}
        if("graph_opt_remove_outliers"==(*_i)->name){graph_opt_remove_outliers = boost::any_cast<bool>(val);}
        if("graph_opt_outlier_weight_threshold"==(*_i)->name){graph_opt_outlier_weight_threshold = boost::any_cast<double>(val);}
        if("graph_opt_min_distance"==(*_i)->name){graph_opt_min_distance = boost::any_cast<int>(val);}
        if("graph_opt_final"==(*_i)->name){graph_opt_final = boost::any_cast<bool>(val);}
        if("graph_opt_final_iterations"==(*_i)->name){graph_opt_final_iterations = boost::any_cast<int>(val);}
        if("graph_opt_final_dense_graph"==(*_i)->name){graph_opt_final_dense_graph = boost::any_cast<bool>(val);}
        if("graph_opt_final_remove_outliers"==(*_i)->name){graph_opt_final_remove_outliers = boost::any_cast<bool>(val);}
        if("graph_opt_final_outlier_weight_threshold"==(*_i)->name){graph_opt_final_outlier_weight_threshold = boost::any_cast<double>(val);}
        if("use_multithreading"==(*_i)->name){use_multithreading = boost::any_cast<bool>(val);}
      }
    }

    double max_translational_distance;
double max_rotational_distance;
double min_entropy_ratio;
double min_eq_sys_constraint_ratio;
double constraint_search_radius;
double constraint_min_entropy_ratio_coarse;
double constraint_min_entropy_ratio_fine;
double constraint_min_eq_sys_constraint_ratio;
bool graph_opt_robust;
int graph_opt_iterations;
bool graph_opt_dense_graph;
bool graph_opt_remove_outliers;
double graph_opt_outlier_weight_threshold;
int graph_opt_min_distance;
bool graph_opt_final;
int graph_opt_final_iterations;
bool graph_opt_final_dense_graph;
bool graph_opt_final_remove_outliers;
double graph_opt_final_outlier_weight_threshold;
bool use_multithreading;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_translational_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_rotational_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_entropy_ratio;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_eq_sys_constraint_ratio;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double constraint_search_radius;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double constraint_min_entropy_ratio_coarse;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double constraint_min_entropy_ratio_fine;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double constraint_min_eq_sys_constraint_ratio;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool graph_opt_robust;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int graph_opt_iterations;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool graph_opt_dense_graph;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool graph_opt_remove_outliers;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double graph_opt_outlier_weight_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int graph_opt_min_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool graph_opt_final;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int graph_opt_final_iterations;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool graph_opt_final_dense_graph;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool graph_opt_final_remove_outliers;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double graph_opt_final_outlier_weight_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool use_multithreading;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("KeyframeSlamConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const KeyframeSlamConfig &__max__ = __getMax__();
      const KeyframeSlamConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const KeyframeSlamConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const KeyframeSlamConfig &__getDefault__();
    static const KeyframeSlamConfig &__getMax__();
    static const KeyframeSlamConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const KeyframeSlamConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void KeyframeSlamConfig::ParamDescription<std::string>::clamp(KeyframeSlamConfig &config, const KeyframeSlamConfig &max, const KeyframeSlamConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class KeyframeSlamConfigStatics
  {
    friend class KeyframeSlamConfig;

    KeyframeSlamConfigStatics()
    {
KeyframeSlamConfig::GroupDescription<KeyframeSlamConfig::DEFAULT, KeyframeSlamConfig> Default("Default", "", 0, 0, true, &KeyframeSlamConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_translational_distance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_translational_distance = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_translational_distance = 0.3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("max_translational_distance", "double", 1, "", "", &KeyframeSlamConfig::max_translational_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("max_translational_distance", "double", 1, "", "", &KeyframeSlamConfig::max_translational_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_rotational_distance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_rotational_distance = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_rotational_distance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("max_rotational_distance", "double", 1, "", "", &KeyframeSlamConfig::max_rotational_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("max_rotational_distance", "double", 1, "", "", &KeyframeSlamConfig::max_rotational_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_entropy_ratio = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_entropy_ratio = 1.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_entropy_ratio = 0.4;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("min_entropy_ratio", "double", 1, "", "", &KeyframeSlamConfig::min_entropy_ratio)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("min_entropy_ratio", "double", 1, "", "", &KeyframeSlamConfig::min_entropy_ratio)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_eq_sys_constraint_ratio = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_eq_sys_constraint_ratio = 1.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_eq_sys_constraint_ratio = 0.3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("min_eq_sys_constraint_ratio", "double", 1, "", "", &KeyframeSlamConfig::min_eq_sys_constraint_ratio)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("min_eq_sys_constraint_ratio", "double", 1, "", "", &KeyframeSlamConfig::min_eq_sys_constraint_ratio)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.constraint_search_radius = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.constraint_search_radius = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.constraint_search_radius = 0.75;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("constraint_search_radius", "double", 1, "", "", &KeyframeSlamConfig::constraint_search_radius)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("constraint_search_radius", "double", 1, "", "", &KeyframeSlamConfig::constraint_search_radius)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.constraint_min_entropy_ratio_coarse = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.constraint_min_entropy_ratio_coarse = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.constraint_min_entropy_ratio_coarse = 0.7;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("constraint_min_entropy_ratio_coarse", "double", 1, "", "", &KeyframeSlamConfig::constraint_min_entropy_ratio_coarse)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("constraint_min_entropy_ratio_coarse", "double", 1, "", "", &KeyframeSlamConfig::constraint_min_entropy_ratio_coarse)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.constraint_min_entropy_ratio_fine = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.constraint_min_entropy_ratio_fine = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.constraint_min_entropy_ratio_fine = 0.9;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("constraint_min_entropy_ratio_fine", "double", 1, "", "", &KeyframeSlamConfig::constraint_min_entropy_ratio_fine)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("constraint_min_entropy_ratio_fine", "double", 1, "", "", &KeyframeSlamConfig::constraint_min_entropy_ratio_fine)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.constraint_min_eq_sys_constraint_ratio = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.constraint_min_eq_sys_constraint_ratio = 1.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.constraint_min_eq_sys_constraint_ratio = 0.3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("constraint_min_eq_sys_constraint_ratio", "double", 1, "", "", &KeyframeSlamConfig::constraint_min_eq_sys_constraint_ratio)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("constraint_min_eq_sys_constraint_ratio", "double", 1, "", "", &KeyframeSlamConfig::constraint_min_eq_sys_constraint_ratio)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_robust = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_robust = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_robust = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_robust", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_robust)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_robust", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_robust)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_iterations = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_iterations = 500;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_iterations = 20;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<int>("graph_opt_iterations", "int", 1, "", "", &KeyframeSlamConfig::graph_opt_iterations)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<int>("graph_opt_iterations", "int", 1, "", "", &KeyframeSlamConfig::graph_opt_iterations)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_dense_graph = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_dense_graph = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_dense_graph = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_dense_graph", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_dense_graph)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_dense_graph", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_dense_graph)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_remove_outliers = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_remove_outliers = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_remove_outliers = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_remove_outliers", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_remove_outliers)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_remove_outliers", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_remove_outliers)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_outlier_weight_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_outlier_weight_threshold = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_outlier_weight_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("graph_opt_outlier_weight_threshold", "double", 1, "", "", &KeyframeSlamConfig::graph_opt_outlier_weight_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("graph_opt_outlier_weight_threshold", "double", 1, "", "", &KeyframeSlamConfig::graph_opt_outlier_weight_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_min_distance = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_min_distance = 500;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_min_distance = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<int>("graph_opt_min_distance", "int", 1, "", "", &KeyframeSlamConfig::graph_opt_min_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<int>("graph_opt_min_distance", "int", 1, "", "", &KeyframeSlamConfig::graph_opt_min_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_final = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_final = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_final = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_final", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_final)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_final", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_final)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_final_iterations = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_final_iterations = 5000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_final_iterations = 1000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<int>("graph_opt_final_iterations", "int", 1, "", "", &KeyframeSlamConfig::graph_opt_final_iterations)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<int>("graph_opt_final_iterations", "int", 1, "", "", &KeyframeSlamConfig::graph_opt_final_iterations)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_final_dense_graph = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_final_dense_graph = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_final_dense_graph = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_final_dense_graph", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_final_dense_graph)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_final_dense_graph", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_final_dense_graph)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_final_remove_outliers = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_final_remove_outliers = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_final_remove_outliers = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_final_remove_outliers", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_final_remove_outliers)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("graph_opt_final_remove_outliers", "bool", 1, "", "", &KeyframeSlamConfig::graph_opt_final_remove_outliers)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.graph_opt_final_outlier_weight_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.graph_opt_final_outlier_weight_threshold = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.graph_opt_final_outlier_weight_threshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("graph_opt_final_outlier_weight_threshold", "double", 1, "", "", &KeyframeSlamConfig::graph_opt_final_outlier_weight_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<double>("graph_opt_final_outlier_weight_threshold", "double", 1, "", "", &KeyframeSlamConfig::graph_opt_final_outlier_weight_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.use_multithreading = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.use_multithreading = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.use_multithreading = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("use_multithreading", "bool", 1, "", "", &KeyframeSlamConfig::use_multithreading)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KeyframeSlamConfig::AbstractParamDescriptionConstPtr(new KeyframeSlamConfig::ParamDescription<bool>("use_multithreading", "bool", 1, "", "", &KeyframeSlamConfig::use_multithreading)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(KeyframeSlamConfig::AbstractGroupDescriptionConstPtr(new KeyframeSlamConfig::GroupDescription<KeyframeSlamConfig::DEFAULT, KeyframeSlamConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<KeyframeSlamConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<KeyframeSlamConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<KeyframeSlamConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    KeyframeSlamConfig __max__;
    KeyframeSlamConfig __min__;
    KeyframeSlamConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const KeyframeSlamConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static KeyframeSlamConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &KeyframeSlamConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const KeyframeSlamConfig &KeyframeSlamConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const KeyframeSlamConfig &KeyframeSlamConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const KeyframeSlamConfig &KeyframeSlamConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<KeyframeSlamConfig::AbstractParamDescriptionConstPtr> &KeyframeSlamConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<KeyframeSlamConfig::AbstractGroupDescriptionConstPtr> &KeyframeSlamConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const KeyframeSlamConfigStatics *KeyframeSlamConfig::__get_statics__()
  {
    const static KeyframeSlamConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = KeyframeSlamConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __KEYFRAMESLAMRECONFIGURATOR_H__
