// Generated by gencpp from file dvo_slam/PoseStampedArray.msg
// DO NOT EDIT!


#ifndef DVO_SLAM_MESSAGE_POSESTAMPEDARRAY_H
#define DVO_SLAM_MESSAGE_POSESTAMPEDARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace dvo_slam
{
template <class ContainerAllocator>
struct PoseStampedArray_
{
  typedef PoseStampedArray_<ContainerAllocator> Type;

  PoseStampedArray_()
    : poses()  {
    }
  PoseStampedArray_(const ContainerAllocator& _alloc)
    : poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::dvo_slam::PoseStampedArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dvo_slam::PoseStampedArray_<ContainerAllocator> const> ConstPtr;

}; // struct PoseStampedArray_

typedef ::dvo_slam::PoseStampedArray_<std::allocator<void> > PoseStampedArray;

typedef boost::shared_ptr< ::dvo_slam::PoseStampedArray > PoseStampedArrayPtr;
typedef boost::shared_ptr< ::dvo_slam::PoseStampedArray const> PoseStampedArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dvo_slam::PoseStampedArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dvo_slam::PoseStampedArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dvo_slam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dvo_slam': ['/home/smarlogy/catkin_ws/src/dvo_slam/dvo_slam/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dvo_slam::PoseStampedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dvo_slam::PoseStampedArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dvo_slam::PoseStampedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dvo_slam::PoseStampedArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dvo_slam::PoseStampedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dvo_slam::PoseStampedArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dvo_slam::PoseStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4bbbec105a3dc69d6c5974def547813";
  }

  static const char* value(const ::dvo_slam::PoseStampedArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4bbbec105a3dc69ULL;
  static const uint64_t static_value2 = 0xd6c5974def547813ULL;
};

template<class ContainerAllocator>
struct DataType< ::dvo_slam::PoseStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dvo_slam/PoseStampedArray";
  }

  static const char* value(const ::dvo_slam::PoseStampedArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dvo_slam::PoseStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped[] poses\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::dvo_slam::PoseStampedArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dvo_slam::PoseStampedArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseStampedArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dvo_slam::PoseStampedArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dvo_slam::PoseStampedArray_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DVO_SLAM_MESSAGE_POSESTAMPEDARRAY_H
