(cl:defpackage marker_msgs-msg
  (:use )
  (:export
   "<FIDUCIAL>"
   "FIDUCIAL"
   "<FIDUCIALDETECTION>"
   "FIDUCIALDETECTION"
   "<MARKER>"
   "MARKER"
   "<MARKERDETECTION>"
   "MARKERDETECTION"
   "<MARKERSTAMPED>"
   "MARKERSTAMPED"
   "<MARKERWITHCOVARIANCE>"
   "MARKERWITHCOVARIANCE"
   "<MARKERWITHCOVARIANCEARRAY>"
   "MARKERWITHCOVARIANCEARRAY"
   "<MARKERWITHCOVARIANCESTAMPED>"
   "MARKERWITHCOVARIANCESTAMPED"
  ))

